factions:
- casai
- highfall
- tidal


add "dusps" to {factions::*}
	set {fac.name::dusps} to "Kingdom of Dusps"
	set {fac.color::dusps} to "<##9A5CC6>"
	set {fac.color.map::dusps} to "#9A5CC6"
	set {fac.coloredname::dusps} to concat({fac.color::dusps}, {fac.name::dusps})

	add "insohm" to {factions::*}
	set {fac.name::insohm} to "Insohmic Commonwealth"
	set {fac.color::insohm} to "<##CECACA>"
	set {fac.color.map::insohm} to "#CECACA"
	set {fac.coloredname::insohm} to concat({fac.color::insohm}, {fac.name::insohm}) 

	add "tidal" to {factions::*}
	set {fac.name::tidal} to "Tidal Dinasty"
	set {fac.color::tidal} to "<##2CBAA8>"
	set {fac.color.map::tidal} to "#CECACA"
	set {fac.coloredname::tidal} to concat({fac.color::tidal}, {fac.name::tidal}) 

	add "maelihs" to {factions::*}
	set {fac.name::maelihs} to "Maelihs's Empire"
	set {fac.color::maelihs} to "<##971607>"
	set {fac.color.map::maelihs} to "#971607"
	set {fac.coloredname::maelihs} to concat({fac.color::maelihs}, {fac.name::maelihs}) 
	
	add "casai" to {factions::*}
	set {fac.name::casai} to "Casain Empire"
	set {fac.color::casai} to "<##ff9100>"
	set {fac.color.map::casai} to "#ff9100"
	set {fac.coloredname::casai} to concat({fac.color::casai}, {fac.name::casai}) 

	add "merijool" to {factions::*}
	set {fac.name::merijool} to "Republic of Merijool"
	set {fac.color::merijool} to "<##B4684D>"
	set {fac.color.map::merijool} to "#573224"
	set {fac.coloredname::merijool} to concat({fac.color::merijool}, {fac.name::merijool}) 

	add "gozak" to {factions::*}
	set {fac.name::gozak} to "Gozaki Union"
	set {fac.color::gozak} to "<##47A036>"
	set {fac.color.map::gozak} to "#47A036"
	set {fac.coloredname::gozak} to concat({fac.color::gozak}, {fac.name::gozak}) 

	add "highfall" to {factions::*}
	set {fac.name::highfall} to "Kingdom of Highfall"
	set {fac.color::highfall} to "<##DEB12D>"
	set {fac.color.map::highfall} to "#DEB12D"
	set {fac.coloredname::highfall} to concat({fac.color::highfall}, {fac.name::highfall}) 

	add "drehnoha" to {factions::*}
	set {fac.name::drehnoha} to "United Townships of Dreh'Noha"
	set {fac.color::drehnoha} to "<##769953>"
	set {fac.color.map::drehnoha} to "#769953"
	set {fac.coloredname::drehnoha} to concat({fac.color::drehnoha}, {fac.name::drehnoha}) 

	add "faehrcyliank" to {factions::*}
	set {fac.name::faehrcyliank} to "Federation of Faehrcylian Kingdoms"
	set {fac.color::faehrcyliank} to "<##21497B>"
	set {fac.color.map::faehrcyliank} to "#21497B"
	set {fac.coloredname::faehrcyliank} to concat({fac.color::faehrcyliank}, {fac.name::faehrcyliank}) 

	add "faehrcyliant" to {factions::*}
	set {fac.name::faehrcyliant} to "United Faehrcylian Tribes"
	set {fac.color::faehrcyliant} to "<##906543>"
	set {fac.color.map::faehrcyliant} to "#906543"
	set {fac.coloredname::faehrcyliant} to concat({fac.color::faehrcyliant}, {fac.name::faehrcyliant}) 